name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
predev = "prisma generate && prisma migrate deploy"
dev = "npm exec remix vite:dev"
prebuild = "prisma generate"
build = "npm exec remix vite:build"
